SHELL := /bin/bash

.PHONY: service

service:
	@TARGET_DIR="$(TARGET_DIR)" \
	SERVICE_NAME="$(SERVICE_NAME)" \
	MODULE_PATH="$(MODULE_PATH)" \
	HTTP_ENABLED="$(HTTP_ENABLED)" \
	GRPC_ENABLED="$(GRPC_ENABLED)" \
	PG_ENABLED="$(PG_ENABLED)" \
	KAFKA_ENABLED="$(KAFKA_ENABLED)" \
	KAFKA_PRODUCER_ENABLED="$(KAFKA_PRODUCER_ENABLED)" \
	KAFKA_CONSUMER_ENABLED="$(KAFKA_CONSUMER_ENABLED)" \
	DOCKER_ENABLED="$(DOCKER_ENABLED)" \
	./scripts/service.sh
